### ISSUE TITLE
Does not recognize ".md" as Markdown

### ISSUE THREAD

**Issue by mgedmin** [hhatto/meow#3]
```
$ meow  README.md 
".md" is unsupported markup type.

[SUPPORT FILETYPE]
  textile: textile|txtile
  rst: rst|rest
  markdown: markdown|md|mdown|mkd|mkdn
```

Interestingly, it lists "md" among the extensions for markdown.

```
$ meow --version
0.3
```

**Comment by mgedmin** [comment]
meow 0.4.2 still talks about hoedown:
![ekrano nuotrauka is 2015-04-21 09 31 58](https://cloud.githubusercontent.com/assets/159967/7246683/4868ae0a-e809-11e4-962e-64e5ad8e3c47.png)

**Comment by hhatto** [comment]
@mgedmin thx
